from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.file_3do import File3do
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.file_3ds import File3ds
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.torrent import TorrentFile
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.ttf import TrueTypeFontFile
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.chm import ChmFile
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.lnk import LnkFile
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.pcf import PcfFile
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.ole2 import OLE2_File
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.pdf import PDFDocument
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.pifv import PIFVFile
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.hlp import HlpFile
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.gnome_keyring import GnomeKeyring
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.bplist import BPList
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.dsstore import DSStore
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.word_doc import WordDocumentParser
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.word_2 import Word2DocumentParser
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.mstask import MSTaskFile
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.androidxml import AndroidXMLFile
from openerp.addons.bou_slide_backend_ext.hachoir_parser.misc.mapsforge_map import MapsforgeMapFile
